### ISSUE TITLE
Request admin api port failed

### ISSUE THREAD

**Issue by boboox** [onflow/flow-emulator#145] opened 2022-04-12 05:01 UTC
### Instruction

Local env before: cli v0.32.3 + fcl v0.0.77 + dev-wallet + emulator and everything is  fine.
When I try to upgrade @onflow/fcl to 1.0.0-alpha.1 , before each script ,sdk-send-http.module.js send a request to http://localhost:8080/v1/scripts, this request failed.

upgrade cli to v0.33.1 ,the same problem;
access to testnet, the same problem;

### Problem
request  
http://localhost:8080/v1/scripts?block_height=sealed

response: status code 500
```
gRPC requires HTTP/2
```
<img width="459" alt="WeChatc89c51165069e13abcbb5b728ca197c7" src="https://user-images.githubusercontent.com/11472545/162883662-70e63303-33b7-4ae0-bb1d-a68ab78a5a08.png">
<img width="1130" alt="WeChat8a0982c85aec5137805fbbfc6c487b93" src="https://user-images.githubusercontent.com/11472545/162883713-c3128f5d-0dee-423f-8296-c2059abad9fd.png">

**Comment by sideninja** [comment] 2022-04-12 12:48
Thank you for reporting this, I will try to reproduce this issue and get back to you shortly. It looks like some serious regression happened.

**Comment by josh-onchain** [comment] 2022-05-10 19:39
I think this is still an issue just want to confirm?

**Comment by sideninja** [comment] 2022-05-11 09:57
You should configure to use the port `8888` as that is the port used for HTTP API. Moving to FCL alpha uses HTTP API instead of gRPC API so the access node API needs to be changed accordingly.

**Closed by sideninja** 2022-05-11 09:57 UTC
Labels: Bug, Feedback, L1
