### ISSUE TITLE
Transferring Tokens to a non-existent account kills the emulator.

### ISSUE THREAD

**Issue by ever0de** [onflow/flow-emulator#146] opened 2022-04-23 05:23 UTC
### Instructions

Please fill out the template below to the best of your ability and include a label indicating which tool/service you were working with when you encountered the problem.

### Problem

Sending tokens to an account that doesn't exist in the emulator (which exists on the testnet) gives the below error log and doesn't work anymore.
(It is not forcibly terminated, but it maintains a pending state indefinitely)

### Steps to Reproduce

```shell
ERRO[0011] Failed to commit block error="[Failure Code: 2000] unknown failure: transaction invocation failed when executing transaction: fatal error: storage error: storage address allocation failed: failed to store the key storage index: failed to update storage used by key #73746f726167655f696e646578 on account e8f6dc7f3c13c0a0: account e8f6dc7f3c13c0a0 storage used is not initialized or not initialized correctly"
```

**Comment by bluesign** [comment] 2022-09-12 08:04
Dupe of https://github.com/onflow/flow-emulator/issues/148 

Closed

**Closed** 2022-09-12 08:24 UTC
Labels: Feedback
